version: "3.7"

services:
  database:
    image: postgres
    container_name: seubarriga
    restart:  always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seubarriga
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local